/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL ?? "https://blsanpzzwcmlfvbnfybf.supabase.co";
export const projectId = supabaseUrl.replace("https://", "").replace(".supabase.co", "");
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsc2FucHp6d2NtbGZ2Ym5meWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY0MzY5MDksImV4cCI6MjEwMjAxMjkwOX0.J_HOErCeYznR1zDiY7NkF77hpp6ocFH1Z6FBPDPXzw4";
